const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { createReviewBundle } = require('../src/review-bundle');
const { prepareReview, validateResponse } = require('../src/review');
function bundle(root) { const file = path.join(root, 'input.md'); fs.writeFileSync(file, 'spec\n'); execFileSync('git', ['init', '-q', root]); execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); execFileSync('git', ['-C', root, 'add', 'input.md']); execFileSync('git', ['-C', root, 'commit', '-qm', 'fixture']); const revision = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); const digest = require('../src/artifact-digest').workingTreeDigest(file); const objectId = execFileSync('git', ['-C', root, 'rev-parse', `HEAD:input.md`], { encoding: 'utf8' }).trim(); return createReviewBundle({ task_id: 't1', issue_id: '10', base_revision: revision, target_revision: revision, iteration: 1, conversation: { identity: 'c1', role: 'review' }, project: { identity: 'p', workspace: root, repository: 'r' }, inputs: [{ path: 'input.md', revision, hash_basis: digest.basis, digest: digest.value, byte_length: digest.byte_length, git_object_id: { algorithm: 'git-sha1', basis: 'git_object_id', value: objectId } }], allowed_metadata_revision: 'approval-1', approval_receipt: { digest: 'approval-1', type: 'human_approval', revision }, presentation_receipt: { digest: 'presentation-1', type: 'human_presentation' } }); }
test('review preflight succeeds and response is bound', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); const context = { target_revision: b.target_revision, base_revision: b.base_revision, approvalDigest: 'approval-1', workspaceRoot: root, project: b.project, reviewTaskId: b.task_id, expectedInputRevision: b.target_revision, expectedPresentationDigest: 'presentation-1', expectedIteration: 1 }; assert.equal(prepareReview(b, context).ok, true); assert.equal(validateResponse({ task_id: 't1', iteration: 1, target_revision: b.target_revision, overall_disposition: 'CHANGES_REQUIRED', blocks_progress: true, findings: [{ finding_id: 'F1', severity: 'High', evidence_path: 'x', disposition: 'open' }] }, b).ok, true); });
test('changed input fails before send', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); fs.writeFileSync(path.join(root, 'input.md'), 'changed\n'); const result = require('../src/review-preflight').preflight(b, { workspaceRoot: root, project: b.project, reviewTaskId: b.task_id, expectedInputRevision: b.target_revision, expectedPresentationDigest: 'presentation-1', expectedIteration: 1, approvalDigest: 'approval-1', target_revision: b.target_revision, base_revision: b.base_revision }); assert.equal(result.ok, false); assert.ok(result.errors.includes('INPUT_DIGEST_MISMATCH:input.md')); });
test('stale approval and metadata binding fail closed', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); b.approval_receipt.revision = 'different'; b.allowed_metadata_revision = 'different'; const result = require('../src/review-preflight').preflight(b, {}); assert.equal(result.ok, false); assert.ok(result.errors.includes('APPROVAL_REVISION_MISMATCH')); assert.ok(result.errors.includes('METADATA_APPROVAL_MISMATCH')); });
test('secret and duplicate input fail closed', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); b.secret_token = 'redacted'; b.inputs.push({ ...b.inputs[0] }); const result = require('../src/review-preflight').preflight(b, {}); assert.equal(result.ok, false); assert.ok(result.errors.includes('SECRET_DETECTED')); assert.ok(result.errors.includes('DUPLICATE_INPUT_PATH')); });
