const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createReviewBundle } = require('../src/review-bundle');
const { prepareReview, validateResponse } = require('../src/review');
function bundle(root) { const file = path.join(root, 'input.md'); fs.writeFileSync(file, 'spec\n'); const digest = require('../src/artifact-digest').workingTreeDigest(file); return createReviewBundle({ task_id: 't1', issue_id: '10', base_revision: 'abcdef1234567', target_revision: 'abcdef1234567', iteration: 1, conversation: { identity: 'c1', role: 'review' }, project: { identity: 'p', workspace: 'w', repository: 'r' }, inputs: [{ path: 'input.md', revision: 'abcdef1234567', hash_basis: digest.basis, digest: digest.value, byte_length: digest.byte_length }], allowed_metadata_revision: 'approval-1', approval_receipt: { digest: 'approval-1', type: 'human_approval', revision: 'abcdef1234567' }, presentation_receipt: { digest: 'presentation-1', type: 'human_presentation' } }); }
test('review preflight succeeds and response is bound', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); assert.equal(prepareReview(b, { target_revision: b.target_revision, approvalDigest: 'approval-1' }).ok, true); assert.equal(validateResponse({ task_id: 't1', iteration: 1, target_revision: b.target_revision, overall_disposition: 'CHANGES_REQUIRED', blocks_progress: true, findings: [{ finding_id: 'F1', severity: 'High', evidence_path: 'x', disposition: 'open' }] }, b).ok, true); });
test('unverifiable input revision fails before send', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); fs.writeFileSync(path.join(root, 'input.md'), 'changed\n'); const result = require('../src/review-preflight').preflight(b, { workspaceRoot: root }); assert.equal(result.ok, false); assert.ok(result.errors.includes('INPUT_UNREADABLE:input.md')); });
test('stale approval and metadata binding fail closed', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); b.approval_receipt.revision = 'different'; b.allowed_metadata_revision = 'different'; const result = require('../src/review-preflight').preflight(b, {}); assert.equal(result.ok, false); assert.ok(result.errors.includes('APPROVAL_REVISION_MISMATCH')); assert.ok(result.errors.includes('METADATA_APPROVAL_MISMATCH')); });
test('secret and duplicate input fail closed', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'review-')); const b = bundle(root); b.secret_token = 'redacted'; b.inputs.push({ ...b.inputs[0] }); const result = require('../src/review-preflight').preflight(b, {}); assert.equal(result.ok, false); assert.ok(result.errors.includes('SECRET_DETECTED')); assert.ok(result.errors.includes('DUPLICATE_INPUT_PATH')); });
