const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { initialState, advance, approvePlan } = require('../src/workflow.cjs');
const { assertImplementationAllowed } = require('../src/workflow-gates.cjs');
const { advanceStage } = require('../src/model.cjs');
const { TASK_ROLES, assertImplementationTask } = require('../src/task-roles.cjs');
const { createOrchestrator } = require('../src/orchestrator.cjs');
const { ChildTaskRunner } = require('../src/child-task-runner.cjs');
const { validateStageEvidence } = require('../src/stage-evidence.cjs');
function evidence(root, stage, revision, role = 'orchestrator') { const recordPath = path.join(root, 'records', `${stage}.json`); fs.mkdirSync(path.dirname(recordPath), { recursive: true }); const { workingTreeDigest } = require('../src/artifact-digest.cjs'); let record; if (stage === 'plan_review') { const reviewRecords = []; for (const round of [1, 2, 3]) { const reviewPath = path.join(root, 'records', `plan-review-${round}.json`); fs.writeFileSync(reviewPath, JSON.stringify({ round, verdict: 'APPROVE', plan_digest: 'plan-digest', source_revision: revision })); reviewRecords.push({ record_path: path.relative(root, reviewPath), artifact_digest: workingTreeDigest(reviewPath).value, round, verdict: 'APPROVE', plan_digest: 'plan-digest' }); } const receiptPath = path.join(root, 'records', 'plan-approval.json'); fs.writeFileSync(receiptPath, JSON.stringify({ type: 'human_approval', approved_revision: revision, plan_digest: 'plan-digest' })); record = { stage, source_revision: revision, conversation_role: role, plan_digest: 'plan-digest', review_records: reviewRecords, human_approval_receipt_path: path.relative(root, receiptPath) }; } else record = { stage, source_revision: revision, conversation_role: role }; fs.writeFileSync(recordPath, JSON.stringify(record)); return { artifact_digest: workingTreeDigest(recordPath).value, source_revision: revision, record_path: path.relative(root, recordPath), conversation_role: role }; }
test('workflow follows fail-closed transitions', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workflow-')); fs.writeFileSync(path.join(root, 'seed.txt'), 'seed'); require('node:child_process').execFileSync('git', ['init', '-q', root]); require('node:child_process').execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); require('node:child_process').execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); require('node:child_process').execFileSync('git', ['-C', root, 'add', 'seed.txt']); require('node:child_process').execFileSync('git', ['-C', root, 'commit', '-qm', 'seed']); const revision = require('node:child_process').execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); let s = initialState('w', revision); assert.throws(() => advance(s, 'approved'), /INVALID_TRANSITION/); s = advance(s, 'preflighted', { preflight_passed: true }); for (const stage of ['prototype_intake', 'prototype_design', 'prototype_review', 'prototype_execution', 'specification', 'issue_approval', 'planning', 'plan_review']) s = advanceStage(s, stage, evidence(root, stage, revision), { workspaceRoot: root }); s = approvePlan(s, { plan_approved: true, approved_revision: revision, approval_receipt: { actor: 'human', id: 'approval-1' } }); s = advanceStage(s, 'implementation', evidence(root, 'implementation', revision), { workspaceRoot: root }); assert.doesNotThrow(() => assertImplementationAllowed(s)); });
test('implementation requires approval and same revision', () => { assert.throws(() => assertImplementationAllowed({ stage: 'implementation', status: 'reviewing', plan_approved: false, target_revision: 'revision', approved_revision: 'revision' }), /IMPLEMENTATION_STATUS_REQUIRED/); assert.throws(() => assertImplementationAllowed({ stage: 'implementation', status: 'approved', plan_approved: true, target_revision: 'revision', approved_revision: 'other-revision' }), /APPROVED_REVISION_MISMATCH/); });
test('workflow rejects skipped gates', () => { let s = initialState('w', 'revision'); assert.throws(() => advance(s, 'preflighted'), /PREFLIGHT_REQUIRED/); s = advance(s, 'preflighted', { preflight_passed: true }); assert.throws(() => advance(s, 'reviewing'), /STATUS_STAGE_MISMATCH/); assert.throws(() => advance(s, 'reviewing', { stage: 'plan_review' }), /PROTECTED_STATE_PATCH/); assert.throws(() => advanceStage(s, 'prototype_execution', {}, { workspaceRoot: process.cwd() }), /INVALID_STAGE_TRANSITION/); });
test('stage transitions cannot skip required status gates', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workflow-status-')); const git = require('node:child_process'); fs.writeFileSync(path.join(root, 'seed.txt'), 'seed'); git.execFileSync('git', ['init', '-q', root]); git.execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); git.execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); git.execFileSync('git', ['-C', root, 'add', 'seed.txt']); git.execFileSync('git', ['-C', root, 'commit', '-qm', 'seed']); const revision = git.execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); assert.throws(() => advanceStage(initialState('w', revision), 'prototype_intake', evidence(root, 'prototype_intake', revision), { workspaceRoot: root }), /STAGE_STATUS_PRECONDITION/); });
test('workflow stage harness rejects skipped stages and missing evidence', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workflow-stage-')); let s = initialState('w', 'revision'); assert.throws(() => advanceStage(s, 'prototype_execution', {}, { workspaceRoot: root }), /INVALID_STAGE_TRANSITION/); assert.throws(() => advanceStage(s, 'prototype_intake', {}, { workspaceRoot: root }), /STAGE_EVIDENCE_REQUIRED/); });
test('orchestrator refuses implementation without verified prior evidence', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'orchestrator-')); const runner = new ChildTaskRunner((task, worktree) => ({ task_id: task.task_id, worktree_root: worktree.worktree_root })); const orchestrator = createOrchestrator(root, runner); assert.throws(() => orchestrator.delegateImplementation({ task_id: 'o', role: TASK_ROLES.ORCHESTRATOR }, { lifecycle: 'running', worktree_root: 'child' }), /IMPLEMENTATION_TASK_REQUIRED/); fs.mkdirSync(path.join(root, '.workflow-state'), { recursive: true }); const now = new Date().toISOString(); fs.writeFileSync(path.join(root, '.workflow-state', 'workflow-state.json'), JSON.stringify({ schema_version: '1.0.0', workflow_id: 'w', target_revision: 'revision', status: 'approved', stage: 'implementation', evidence: {}, plan_approved: true, preflight_passed: true, approved_revision: 'revision', approval_receipt: { actor: 'human' }, created_at: now, updated_at: now })); assert.throws(() => orchestrator.delegateImplementation({ task_id: 'impl-1', parent_task_id: 'o', role: TASK_ROLES.IMPLEMENTATION }, { lifecycle: 'running', worktree_root: 'child' }), /STAGE_EVIDENCE_CHAIN_REQUIRED/); assert.throws(() => assertImplementationTask({ task_id: 'impl-1', parent_task_id: 'impl-1', role: TASK_ROLES.IMPLEMENTATION }), /TASK_PARENT_SELF_REFERENCE/); });
test('approval fields cannot be injected through generic transition', () => { const s = initialState('w', 'revision'); assert.throws(() => advance(s, 'blocked', { plan_approved: true, approved_revision: 'revision' }), /PROTECTED_STATE_PATCH/); });

test('plan review rejects three NEEDS_WORK records even when an aggregate claims approval', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'plan-review-needs-work-'));
  fs.writeFileSync(path.join(root, 'seed.txt'), 'seed');
  const git = require('node:child_process');
  git.execFileSync('git', ['init', '-q', root]);
  git.execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']);
  git.execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']);
  git.execFileSync('git', ['-C', root, 'add', 'seed.txt']);
  git.execFileSync('git', ['-C', root, 'commit', '-qm', 'seed']);
  const revision = git.execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  fs.mkdirSync(path.join(root, 'records'), { recursive: true });
  const { workingTreeDigest } = require('../src/artifact-digest.cjs');
  const reviews = [];
  for (const round of [1, 2, 3]) { const reviewPath = path.join(root, 'records', `needs-${round}.json`); fs.writeFileSync(reviewPath, JSON.stringify({ round, verdict: 'NEEDS_WORK', plan_digest: 'plan-digest', source_revision: revision })); reviews.push({ record_path: path.relative(root, reviewPath), artifact_digest: workingTreeDigest(reviewPath).value, round, verdict: 'NEEDS_WORK', plan_digest: 'plan-digest' }); }
  const receiptPath = path.join(root, 'records', 'approval.json');
  fs.writeFileSync(receiptPath, JSON.stringify({ type: 'human_approval', approved_revision: revision, plan_digest: 'plan-digest' }));
  const aggregatePath = path.join(root, 'records', 'aggregate.json');
  fs.writeFileSync(aggregatePath, JSON.stringify({ stage: 'plan_review', source_revision: revision, conversation_role: 'orchestrator', qualifying_rounds: 3, verdict: 'APPROVE', human_approval: true, plan_digest: 'plan-digest', review_records: reviews, human_approval_receipt_path: path.relative(root, receiptPath) }));
  assert.throws(() => validateStageEvidence(root, 'plan_review', { artifact_digest: workingTreeDigest(aggregatePath).value, source_revision: revision, record_path: path.relative(root, aggregatePath), conversation_role: 'orchestrator' }, { repositoryRoot: root }), /PLAN_REVIEW_(QUALIFYING_RECORDS_REQUIRED|LATEST_NOT_QUALIFYING)/);
  for (const round of [1, 2, 3]) { const reviewPath = path.join(root, 'records', `needs-${round}.json`); fs.writeFileSync(reviewPath, JSON.stringify({ round, verdict: 'APPROVE', plan_digest: 'plan-digest', source_revision: revision })); reviews[round - 1] = { record_path: path.relative(root, reviewPath), artifact_digest: workingTreeDigest(reviewPath).value, round, verdict: 'APPROVE', plan_digest: 'plan-digest' }; }
  const latestPath = path.join(root, 'records', 'needs-4.json'); fs.writeFileSync(latestPath, JSON.stringify({ round: 4, verdict: 'NEEDS_WORK', plan_digest: 'plan-digest', source_revision: revision }));
  reviews.push({ record_path: path.relative(root, latestPath), artifact_digest: workingTreeDigest(latestPath).value, round: 4, verdict: 'NEEDS_WORK', plan_digest: 'plan-digest' });
  const updatedAggregate = { stage: 'plan_review', source_revision: revision, conversation_role: 'orchestrator', qualifying_rounds: 3, verdict: 'APPROVE', human_approval: true, plan_digest: 'plan-digest', review_records: reviews, human_approval_receipt_path: path.relative(root, receiptPath) };
  fs.writeFileSync(aggregatePath, JSON.stringify(updatedAggregate));
  assert.throws(() => validateStageEvidence(root, 'plan_review', { artifact_digest: workingTreeDigest(aggregatePath).value, source_revision: revision, record_path: path.relative(root, aggregatePath), conversation_role: 'orchestrator' }, { repositoryRoot: root }), /PLAN_REVIEW_LATEST_NOT_QUALIFYING/);
});
