const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { initialState, advance } = require('../src/workflow');
const { assertImplementationAllowed } = require('../src/workflow-gates');
const { advanceStage } = require('../src/model');
const { TASK_ROLES, assertImplementationTask } = require('../src/task-roles');
const { createOrchestrator } = require('../src/orchestrator');
const { ChildTaskRunner } = require('../src/child-task-runner');
function evidence(stage) { return { artifact_digest: `digest-${stage}`, source_revision: 'revision', record_path: `records/${stage}.json`, conversation_role: 'orchestrator' }; }
test('workflow follows fail-closed transitions', () => { let s = initialState('w', 'revision'); assert.throws(() => advance(s, 'approved'), /INVALID_TRANSITION/); s = advance(s, 'preflighted', { preflight_passed: true }); for (const stage of ['prototype_intake', 'prototype_design', 'prototype_review', 'prototype_execution', 'specification', 'issue_approval', 'planning', 'plan_review', 'implementation']) s = advanceStage(s, stage, evidence(stage)); s = { ...s, plan_approved: true, approved_revision: 'revision' }; assert.doesNotThrow(() => assertImplementationAllowed(s)); });
test('implementation requires approval and same revision', () => { assert.throws(() => assertImplementationAllowed({ status: 'reviewing', plan_approved: false, target_revision: 'a', approved_revision: 'a' }), /IMPLEMENTATION_STAGE_REQUIRED/); assert.throws(() => assertImplementationAllowed({ status: 'approved', plan_approved: true, target_revision: 'a', approved_revision: 'b' }), /APPROVED_REVISION_MISMATCH/); });
test('workflow rejects skipped gates', () => { let s = initialState('w', 'revision'); assert.throws(() => advance(s, 'preflighted'), /PREFLIGHT_REQUIRED/); s = advance(s, 'preflighted', { preflight_passed: true }); assert.throws(() => advance(s, 'reviewing'), /STATUS_STAGE_MISMATCH/); assert.throws(() => advanceStage(s, 'prototype_execution', evidence('prototype_execution')), /INVALID_STAGE_TRANSITION/); });
test('workflow stage harness rejects skipped stages and missing evidence', () => { let s = initialState('w', 'revision'); assert.throws(() => advanceStage(s, 'prototype_execution', {}), /INVALID_STAGE_TRANSITION/); s = advanceStage(s, 'prototype_intake', { artifact_digest: 'd', source_revision: 'revision', record_path: 'records/intake.md', conversation_role: 'orchestrator' }); assert.equal(s.stage, 'prototype_intake'); assert.throws(() => advanceStage(s, 'prototype_design', {}), /STAGE_EVIDENCE_REQUIRED/); });
test('orchestrator delegates implementation to an independent implementation task', () => { const runner = new ChildTaskRunner((task, worktree) => ({ task_id: task.task_id, worktree_root: worktree.worktree_root })); const orchestrator = createOrchestrator(fs.mkdtempSync(path.join(os.tmpdir(), 'orchestrator-')), runner); assert.throws(() => orchestrator.delegateImplementation({ task_id: 'o', role: TASK_ROLES.ORCHESTRATOR }, { lifecycle: 'running', worktree_root: 'child' }), /IMPLEMENTATION_TASK_REQUIRED/); assert.deepEqual(orchestrator.delegateImplementation({ task_id: 'impl-1', parent_task_id: 'o', role: TASK_ROLES.IMPLEMENTATION }, { lifecycle: 'running', worktree_root: 'child' }), { task_id: 'impl-1', worktree_root: 'child' }); assert.throws(() => assertImplementationTask({ task_id: 'impl-1', parent_task_id: 'impl-1', role: TASK_ROLES.IMPLEMENTATION }), /TASK_PARENT_SELF_REFERENCE/); });
