const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { initialState, advance, approvePlan } = require('../src/workflow');
const { assertImplementationAllowed } = require('../src/workflow-gates');
const { advanceStage } = require('../src/model');
const { TASK_ROLES, assertImplementationTask } = require('../src/task-roles');
const { createOrchestrator } = require('../src/orchestrator');
const { ChildTaskRunner } = require('../src/child-task-runner');
function evidence(root, stage, revision, role = 'orchestrator') { const recordPath = path.join(root, 'records', `${stage}.json`); fs.mkdirSync(path.dirname(recordPath), { recursive: true }); const record = { stage, source_revision: revision, conversation_role: role, qualifying_rounds: stage === 'plan_review' ? 3 : undefined, verdict: stage === 'plan_review' ? 'APPROVE' : undefined, human_approval: stage === 'plan_review' ? true : undefined, plan_digest: stage === 'plan_review' ? 'plan-digest' : undefined }; fs.writeFileSync(recordPath, JSON.stringify(record)); const { workingTreeDigest } = require('../src/artifact-digest'); return { artifact_digest: workingTreeDigest(recordPath).value, source_revision: revision, record_path: path.relative(root, recordPath), conversation_role: role }; }
test('workflow follows fail-closed transitions', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workflow-')); fs.writeFileSync(path.join(root, 'seed.txt'), 'seed'); require('node:child_process').execFileSync('git', ['init', '-q', root]); require('node:child_process').execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); require('node:child_process').execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); require('node:child_process').execFileSync('git', ['-C', root, 'add', 'seed.txt']); require('node:child_process').execFileSync('git', ['-C', root, 'commit', '-qm', 'seed']); const revision = require('node:child_process').execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); let s = initialState('w', revision); assert.throws(() => advance(s, 'approved'), /INVALID_TRANSITION/); s = advance(s, 'preflighted', { preflight_passed: true }); for (const stage of ['prototype_intake', 'prototype_design', 'prototype_review', 'prototype_execution', 'specification', 'issue_approval', 'planning', 'plan_review']) s = advanceStage(s, stage, evidence(root, stage, revision), { workspaceRoot: root }); s = approvePlan(s, { plan_approved: true, approved_revision: revision, approval_receipt: { actor: 'human', id: 'approval-1' } }); s = advanceStage(s, 'implementation', evidence(root, 'implementation', revision), { workspaceRoot: root }); assert.doesNotThrow(() => assertImplementationAllowed(s)); });
test('implementation requires approval and same revision', () => { assert.throws(() => assertImplementationAllowed({ stage: 'implementation', status: 'reviewing', plan_approved: false, target_revision: 'revision', approved_revision: 'revision' }), /IMPLEMENTATION_STATUS_REQUIRED/); assert.throws(() => assertImplementationAllowed({ stage: 'implementation', status: 'approved', plan_approved: true, target_revision: 'revision', approved_revision: 'other-revision' }), /APPROVED_REVISION_MISMATCH/); });
test('workflow rejects skipped gates', () => { let s = initialState('w', 'revision'); assert.throws(() => advance(s, 'preflighted'), /PREFLIGHT_REQUIRED/); s = advance(s, 'preflighted', { preflight_passed: true }); assert.throws(() => advance(s, 'reviewing'), /STATUS_STAGE_MISMATCH/); assert.throws(() => advance(s, 'reviewing', { stage: 'plan_review' }), /PROTECTED_STATE_PATCH/); assert.throws(() => advanceStage(s, 'prototype_execution', {}, { workspaceRoot: process.cwd() }), /INVALID_STAGE_TRANSITION/); });
test('workflow stage harness rejects skipped stages and missing evidence', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workflow-stage-')); let s = initialState('w', 'revision'); assert.throws(() => advanceStage(s, 'prototype_execution', {}, { workspaceRoot: root }), /INVALID_STAGE_TRANSITION/); assert.throws(() => advanceStage(s, 'prototype_intake', {}, { workspaceRoot: root }), /STAGE_EVIDENCE_REQUIRED/); });
test('orchestrator refuses implementation without verified prior evidence', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'orchestrator-')); const runner = new ChildTaskRunner((task, worktree) => ({ task_id: task.task_id, worktree_root: worktree.worktree_root })); const orchestrator = createOrchestrator(root, runner); assert.throws(() => orchestrator.delegateImplementation({ task_id: 'o', role: TASK_ROLES.ORCHESTRATOR }, { lifecycle: 'running', worktree_root: 'child' }), /IMPLEMENTATION_TASK_REQUIRED/); fs.mkdirSync(path.join(root, '.workflow-state'), { recursive: true }); const now = new Date().toISOString(); fs.writeFileSync(path.join(root, '.workflow-state', 'workflow-state.json'), JSON.stringify({ schema_version: '1.0.0', workflow_id: 'w', target_revision: 'revision', status: 'approved', stage: 'implementation', evidence: {}, plan_approved: true, preflight_passed: true, approved_revision: 'revision', approval_receipt: { actor: 'human' }, created_at: now, updated_at: now })); assert.throws(() => orchestrator.delegateImplementation({ task_id: 'impl-1', parent_task_id: 'o', role: TASK_ROLES.IMPLEMENTATION }, { lifecycle: 'running', worktree_root: 'child' }), /STAGE_EVIDENCE_CHAIN_REQUIRED/); assert.throws(() => assertImplementationTask({ task_id: 'impl-1', parent_task_id: 'impl-1', role: TASK_ROLES.IMPLEMENTATION }), /TASK_PARENT_SELF_REFERENCE/); });
test('approval fields cannot be injected through generic transition', () => { const s = initialState('w', 'revision'); assert.throws(() => advance(s, 'blocked', { plan_approved: true, approved_revision: 'revision' }), /PROTECTED_STATE_PATCH/); });
