const OPERATIONS = ['prototype_design', 'prototype_evaluation', 'production_plan', 'production_plan_refinement', 'independent_plan_review', 'pr_review'];

export function createRequest({ taskId, iteration, operation, workspace, workId, stage, inputs = [], readScope = [], expected }) {
  if (!OPERATIONS.includes(operation)) throw new Error(`unsupported C2C operation: ${operation}`);
  if (!taskId || iteration === undefined || !workspace || !workId || !stage || !expected) throw new Error('C2C request identity is incomplete');
  return { protocol: 'c2c', state: 'INIT', task_id: taskId, iteration, operation, workspace, work_id: workId, stage, inputs, read_scope: readScope, expected };
}

export function sanitizeRequest(request) {
  const forbidden = /token|secret|password|authorization|\.env|private.?key/i;
  const serialized = JSON.stringify(request); if (forbidden.test(serialized)) throw new Error('request contains forbidden secret-like content');
  return request;
}

export function parseResponse(response) {
  if (!response || !['PLAN', 'DONE', 'BLOCKED'].includes(response.state)) throw new Error('invalid C2C response state');
  if (!response.status || !Array.isArray(response.findings ?? [])) throw new Error('invalid C2C response contract');
  return response;
}

export function createFakeC2CAdapter({ responseForMessage = null } = {}) {
  const conversations = new Map();
  const sentMessages = new Set();
  return {
    calls: [],
    async startConversation(input) {
      this.calls.push({ operation: 'startConversation', input });
      const conversation = { project: input.project, conversationId: `conversation-${this.calls.length}`, status: 'ready', responses: [] };
      conversations.set(conversation.conversationId, conversation);
      return conversation;
    },
    async resumeConversation(input) {
      this.calls.push({ operation: 'resumeConversation', input });
      const conversation = conversations.get(input.conversationId);
      if (!conversation) throw new Error('conversation not found');
      return conversation;
    },
    async sendMessage(input) {
      this.calls.push({ operation: 'sendMessage', input });
      const key = `${input.taskId}:${input.iteration}:${input.messageId}`;
      if (sentMessages.has(key)) return { conversationId: input.conversationId, messageId: input.messageId, duplicate: true };
      sentMessages.add(key);
      const conversation = conversations.get(input.conversationId);
      if (!conversation) throw new Error('conversation not found');
      conversation.status = 'completed';
      const response = responseForMessage?.(input) ?? { state: 'DONE', status: 'DONE', findings: [], artifact: `# ${input.messageId}\n\nGenerated by fake C2C adapter.` };
      conversation.responses.push({ responseId: `response-${input.messageId}`, messageId: input.messageId, ...response });
      return { conversationId: input.conversationId, messageId: input.messageId, duplicate: false };
    },
    async waitForResponse(input) { this.calls.push({ operation: 'waitForResponse', input }); return { status: conversations.get(input.conversationId)?.status ?? 'failed' }; },
    async readResponse(input) { this.calls.push({ operation: 'readResponse', input }); return conversations.get(input.conversationId)?.responses.at(-1) ?? null; },
    async getStatus(input) {
      this.calls.push({ operation: 'getStatus', input });
      const conversation = conversations.get(input.conversationId);
      const accepted = input.messageId ? conversation?.responses.some((response) => response.messageId === input.messageId) : undefined;
      return { status: conversation?.status ?? 'failed', messageAccepted: accepted, messageId: input.messageId ?? null };
    },
    async request(request) {
      this.calls.push(request);
      return { state: 'PLAN', status: 'DONE', findings: [], artifact: `# ${request.operation}\n\nGenerated by fake C2C adapter.` };
    }
  };
}

export const CONVERSATION_OPERATIONS = ['startConversation', 'resumeConversation', 'sendMessage', 'waitForResponse', 'readResponse', 'getStatus'];
