const OPERATIONS = ['prototype_design', 'prototype_evaluation', 'production_plan', 'independent_plan_review', 'pr_review'];

export function createRequest({ taskId, iteration, operation, workspace, workId, stage, inputs = [], readScope = [], expected }) {
  if (!OPERATIONS.includes(operation)) throw new Error(`unsupported C2C operation: ${operation}`);
  if (!taskId || iteration === undefined || !workspace || !workId || !stage || !expected) throw new Error('C2C request identity is incomplete');
  return { protocol: 'c2c', state: 'INIT', task_id: taskId, iteration, operation, workspace, work_id: workId, stage, inputs, read_scope: readScope, expected };
}

export function sanitizeRequest(request) {
  const forbidden = /token|secret|password|authorization|\.env|private.?key/i;
  const serialized = JSON.stringify(request); if (forbidden.test(serialized)) throw new Error('request contains forbidden secret-like content');
  return request;
}

export function parseResponse(response) {
  if (!response || !['PLAN', 'DONE', 'BLOCKED'].includes(response.state)) throw new Error('invalid C2C response state');
  if (!response.status || !Array.isArray(response.findings ?? [])) throw new Error('invalid C2C response contract');
  return response;
}

export function createFakeC2CAdapter() {
  return { calls: [], async request(request) { this.calls.push(request); return { state: 'PLAN', status: 'DONE', findings: [], artifact: `# ${request.operation}\n\nGenerated by fake C2C adapter.` }; } };
}
