const { canonicalJson } = require('./canonical');
const Ajv = require('ajv');
const stateValidator = new Ajv({ allErrors: true }).compile(require('../schemas/workflow-state.schema.json'));
const { validateStageEvidence } = require('./stage-evidence');
const PROTECTED_TRANSITION_FIELDS = ['stage','evidence','plan_approved','approved_revision','approval_receipt','plan_digest','issue_id'];
<<<<<<< HEAD
const STAGES = ['prototype_intake','prototype_design','prototype_implementation','prototype_evaluation','promotion_waiting_approval','production_grilling','production_spec_waiting_approval','production_issue_creating','production_issue_waiting_review','production_issue_ready','production_planning','production_plan_review','production_plan_improvement','production_plan_waiting_approval','production_implementation','production_pr_draft','production_pr_review','production_fix','production_publish_waiting_approval','production_published','production_merge_waiting_approval','completed','stopped','blocked'];
const APPROVAL_KINDS = ['prototype_implementation','promotion','production_spec','production_issue_review','production_plan','pr_publish','pr_merge','destructive_operation','spec_change','update','review_conversation_replacement'];
const STATES = ['draft','preflighted','reviewing','approved','completed','blocked','auth_waiting','connection_waiting','result_unknown'];
const WORKFLOW_STAGES = ['onboarding','prototype_intake','prototype_design','prototype_review','prototype_execution','specification','issue_approval','planning','plan_review','implementation','testing','pr_review','publish','merge'];
const STAGE_REQUIREMENTS = Object.fromEntries(WORKFLOW_STAGES.map((s) => [s, ['artifact_digest','source_revision','record_path','conversation_role']]));
const STAGE_STATUSES = { onboarding:['draft','preflighted'], prototype_intake:['draft','reviewing'], prototype_design:['reviewing'], prototype_review:['reviewing'], prototype_execution:['reviewing'], specification:['reviewing'], issue_approval:['reviewing'], planning:['reviewing'], plan_review:['reviewing'], implementation:['approved'], testing:['approved'], pr_review:['approved'], publish:['approved'], merge:['completed'] };
const STAGE_ENTRY_STATUSES = { prototype_intake:['preflighted'], prototype_design:['reviewing'], prototype_review:['reviewing'], prototype_execution:['reviewing'], specification:['reviewing'], issue_approval:['reviewing'], planning:['reviewing'], plan_review:['reviewing'], implementation:['reviewing'], testing:['approved'], pr_review:['approved'], publish:['approved'], merge:['approved'] };
function deriveQualifyingPlanReviewIteration(h, id) { if (!id || !Array.isArray(h)) return 0; const q=h.filter((r)=>r.stage==='production_plan_review'&&r.role==='plan_review'&&r.conversation_id===id&&r.improved===true&&r.dispositions_complete===true); let n=1; for(const r of q){if(r.round!==n)return n-1;n+=1;} return q.length; }
function initialState(projectId, workflowVersion=1) { const now=new Date().toISOString(); return { workflow_version:workflowVersion,schema_version:1,adapter_version:1,orchestrator_id:null,orchestrator_generation:1,orchestrator_status:'ACTIVE',project_id:projectId,work_id:'unassigned',stage:'prototype_intake',status:'ready',agent:'codex',chatgpt_project:'prototype',artifacts:[],base_revision:null,current_revision:null,next_action:'create_concept_brief',stop_reason:null,revision:1,plan_review_iteration:0,qualifying_plan_review_iteration:0,review_history:[],issue_identity:null,connection_binding:null,conversation_registry:{},presentation_receipts:[],active_external_operation:null,review_context:{planning_conversation_id:null,active_plan_review_conversation_id:null,active_plan_review_project_id:null,active_plan_review_history_revision:0,active_plan_review_non_resumable_reason:null,replacement_history:[]},updated_at:now,conversation:{task_id:null,iteration:0,project_id:null,project_url:null,conversation_id:null,conversation_url:null,workspace:null,role:null,stage:null,state:'INIT',last_message_id:null,next_operation:null,failure_reason:null,sent_messages:[]},agent_state:{agent:'codex',stage:'prototype_intake',status:'ready',started_at:now,updated_at:now,waiting_reason:null,next_action:'create_concept_brief',error:null} }; }
function validateState(state) { if(state?.schema_version==='1.0.0'){if(!STATES.includes(state.status))throw new Error(`STATE_STATUS: ${state.status}`);if(!state.workflow_id||!state.target_revision)throw new Error('STATE_IDENTITY_REQUIRED');if(!WORKFLOW_STAGES.includes(state.stage))throw new Error('STATE_STAGE_REQUIRED');if(!state.evidence||typeof state.evidence!=='object')throw new Error('STATE_EVIDENCE_REQUIRED');if(!stateValidator(state))throw new Error(`STATE_SCHEMA_INVALID: ${stateValidator.errors.map((e)=>e.instancePath||e.keyword).join(',')}`);return true;} const req=['workflow_version','project_id','work_id','stage','status','next_action','revision','plan_review_iteration','qualifying_plan_review_iteration','review_history','review_context','updated_at']; const errors=req.filter((k)=>state[k]==null).map((k)=>`${k} is required`);if(!STAGES.includes(state.stage))errors.push(`unknown stage: ${state.stage}`);if(!Array.isArray(state.review_history))errors.push('review_history is invalid');if(!state.review_context||!Array.isArray(state.review_context.replacement_history))errors.push('review_context is invalid');if(!state.agent_state||typeof state.agent_state!=='object')errors.push('agent_state is required');return errors; }
function transition(state,next,patch={}) { validateState(state);if(PROTECTED_TRANSITION_FIELDS.some((k)=>Object.prototype.hasOwnProperty.call(patch,k)))throw new Error('PROTECTED_STATE_PATCH');const allowed={draft:['preflighted','blocked'],preflighted:['reviewing','blocked','auth_waiting','connection_waiting'],reviewing:['approved','blocked','auth_waiting','connection_waiting','result_unknown'],approved:['completed','blocked'],completed:[],blocked:['draft','preflighted'],auth_waiting:['preflighted','blocked'],connection_waiting:['reviewing','blocked'],result_unknown:['reviewing','blocked']};if(!allowed[state.status]?.includes(next))throw new Error(`INVALID_TRANSITION: ${state.status}->${next}`);const c={...state,...patch,status:next,updated_at:new Date().toISOString()};if(STAGE_STATUSES[c.stage]&&!STAGE_STATUSES[c.stage].includes(next))throw new Error(`STATUS_STAGE_MISMATCH: ${next}/${c.stage}`);if(next==='preflighted'&&c.preflight_passed!==true)throw new Error('PREFLIGHT_REQUIRED');if(next==='approved'&&(c.plan_approved!==true||c.approved_revision!==c.target_revision))throw new Error('PLAN_APPROVAL_REQUIRED');return c; }
function advanceStage(state,nextStage,evidence,context={}) { validateState(state);const i=WORKFLOW_STAGES.indexOf(state.stage);if(WORKFLOW_STAGES.indexOf(nextStage)!==i+1)throw new Error(`INVALID_STAGE_TRANSITION: ${state.stage}->${nextStage}`);if(!evidence||STAGE_REQUIREMENTS[nextStage].some((k)=>typeof evidence[k]!=='string'||!evidence[k]))throw new Error(`STAGE_EVIDENCE_REQUIRED: ${nextStage}`);if(!context.workspaceRoot)throw new Error('STAGE_WORKSPACE_REQUIRED');if(STAGE_ENTRY_STATUSES[nextStage]&&!STAGE_ENTRY_STATUSES[nextStage].includes(state.status))throw new Error(`STAGE_STATUS_PRECONDITION: ${state.stage}/${state.status}->${nextStage}`);if(nextStage==='implementation'&&(state.plan_approved!==true||state.approved_revision!==state.target_revision||!state.approval_receipt))throw new Error('PLAN_APPROVAL_REQUIRED');const verified=validateStageEvidence(context.workspaceRoot,nextStage,evidence,{repositoryRoot:context.repositoryRoot??context.workspaceRoot});const c={...state,stage:nextStage,status:STAGE_STATUSES[nextStage][STAGE_STATUSES[nextStage].length-1],evidence:{...state.evidence,[nextStage]:verified},updated_at:new Date().toISOString()};if(!stateValidator(c))throw new Error(`STAGE_EVIDENCE_INVALID: ${stateValidator.errors.map((e)=>e.instancePath||e.keyword).join(',')}`);return c; }
function approvePlan(state, approval) { validateState(state);if(state.stage!=='plan_review'||state.status!=='reviewing')throw new Error('PLAN_REVIEW_STAGE_REQUIRED');if(!approval||approval.plan_approved!==true||approval.approved_revision!==state.target_revision||typeof approval.approval_receipt!=='object')throw new Error('PLAN_APPROVAL_REQUIRED');const c={...state,plan_approved:true,approved_revision:approval.approved_revision,approval_receipt:approval.approval_receipt,updated_at:new Date().toISOString()};if(!stateValidator(c))throw new Error(`STATE_SCHEMA_INVALID: ${stateValidator.errors.map((e)=>e.instancePath||e.keyword).join(',')}`);return c; }
module.exports={STAGES,APPROVAL_KINDS,STATES,WORKFLOW_STAGES,STAGE_REQUIREMENTS,STAGE_STATUSES,STAGE_ENTRY_STATUSES,PROTECTED_TRANSITION_FIELDS,deriveQualifyingPlanReviewIteration,initialState,validateState,transition,advanceStage,approvePlan,canonicalJson};
=======
const PROTECTED_TRANSITION_FIELDS = ['stage', 'evidence'];
function validateState(state) {
  if (!state || state.schema_version !== '1.0.0') throw new Error('STATE_SCHEMA_VERSION');
  if (!STATES.includes(state.status)) throw new Error(`STATE_STATUS: ${state.status}`);
  if (!state.workflow_id || !state.target_revision) throw new Error('STATE_IDENTITY_REQUIRED');
  if (!WORKFLOW_STAGES.includes(state.stage)) throw new Error('STATE_STAGE_REQUIRED');
  if (!state.evidence || typeof state.evidence !== 'object') throw new Error('STATE_EVIDENCE_REQUIRED');
  if (!stateValidator(state)) throw new Error(`STATE_SCHEMA_INVALID: ${stateValidator.errors.map((error) => error.instancePath || error.keyword).join(',')}`);
  return true;
}
function transition(state, next, patch = {}) {
  validateState(state);
  if (PROTECTED_TRANSITION_FIELDS.some((key) => Object.prototype.hasOwnProperty.call(patch, key))) throw new Error('PROTECTED_STATE_PATCH');
  const allowed = { draft: ['preflighted', 'blocked'], preflighted: ['reviewing', 'blocked', 'auth_waiting', 'connection_waiting'], reviewing: ['approved', 'blocked', 'auth_waiting', 'connection_waiting', 'result_unknown'], approved: ['completed', 'blocked'], completed: [], blocked: ['draft', 'preflighted'], auth_waiting: ['preflighted', 'blocked'], connection_waiting: ['reviewing', 'blocked'], result_unknown: ['reviewing', 'blocked'] };
  if (!allowed[state.status].includes(next)) throw new Error(`INVALID_TRANSITION: ${state.status}->${next}`);
  const candidate = { ...state, ...patch, status: next, updated_at: new Date().toISOString() };
  if (!STAGE_STATUSES[candidate.stage].includes(next)) throw new Error(`STATUS_STAGE_MISMATCH: ${next}/${candidate.stage}`);
  if (next === 'preflighted' && candidate.preflight_passed !== true) throw new Error('PREFLIGHT_REQUIRED');
  if (next === 'approved' && (candidate.plan_approved !== true || candidate.approved_revision !== candidate.target_revision)) throw new Error('PLAN_APPROVAL_REQUIRED');
  return candidate;
}
function advanceStage(state, nextStage, evidence, context = {}) {
  validateState(state);
  const currentIndex = WORKFLOW_STAGES.indexOf(state.stage);
  const nextIndex = WORKFLOW_STAGES.indexOf(nextStage);
  if (nextIndex !== currentIndex + 1) throw new Error(`INVALID_STAGE_TRANSITION: ${state.stage}->${nextStage}`);
  if (!evidence || STAGE_REQUIREMENTS[nextStage].some((key) => typeof evidence[key] !== 'string' || evidence[key].length === 0)) throw new Error(`STAGE_EVIDENCE_REQUIRED: ${nextStage}`);
  if (!context.workspaceRoot) throw new Error('STAGE_WORKSPACE_REQUIRED');
  const verifiedEvidence = validateStageEvidence(context.workspaceRoot, nextStage, evidence, { repositoryRoot: context.repositoryRoot ?? context.workspaceRoot });
  const candidate = { ...state, stage: nextStage, status: STAGE_STATUSES[nextStage][STAGE_STATUSES[nextStage].length - 1], evidence: { ...state.evidence, [nextStage]: verifiedEvidence }, updated_at: new Date().toISOString() };
  if (!stateValidator(candidate)) throw new Error(`STAGE_EVIDENCE_INVALID: ${stateValidator.errors.map((error) => error.instancePath || error.keyword).join(',')}`);
  return candidate;
}
module.exports = { STATES, WORKFLOW_STAGES, STAGE_REQUIREMENTS, STAGE_STATUSES, PROTECTED_TRANSITION_FIELDS, validateState, transition, advanceStage, canonicalJson };
>>>>>>> 072fc7b (Close workflow execution bypasses)
